spring:
  application:
    name: backend
  config:
    import: optional:file:dev.env[.properties]
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      max-lifetime: 170000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 15MB
  # Set https
#  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ${HTTPS_KEY_STORE_PASSWORD}
#    keyStoreType: ${HTTPS_KEY_STORE_TYPE}
#    key-alias: ${HTTPS_KEY_ALIAS}
JWT:
  SECRET-KEY: ${JWT_KEY}

openai:
  model: ${OPENAI_MODEL}
  secret-key: ${OPENAI_API_KEY}